### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by ghost**
- [x] Title pages
- [x] Page 1: Tu peux regarder
- [x] Page 2: Groo
- [x] Page 3: Pas de désherbants
- [x] Page 4: Stop!
- [x] Page 5: C'est impossible
- [x] Page 6: Hi hi hi
- [x] Page 7: On va s'entendre, toi et moi
- [x] Patreon page

@Willem3141: https://mensuel.framapad.org/p/peppercarrot-ep18-dutch

### CODE REVIEW

**Comment by Willem3141** [comment]
Thanks for creating this; I'll look at this tonight or tomorrow.

**Comment by Willem3141** [comment]
@M1dgard I made a first version of the translation in the shared document.

All those onomatopoeia... they are hard to translate well :wink:

**Comment by ghost** [comment]
Nou nou, I made some small adjustments but overall the translation is very nice!

> All those onomatopoeia... they are hard to translate well :wink: 

I think you did a good job. :smiley:

**Comment by Willem3141** [comment]
Thank you! I copied the translation into the SVG files and pushed it, so I think we are done now.

> Nou nou

Oh no! Another one? I just keep on saying that :laughing:

**Comment by ghost** [comment]
> Oh no! Another one? I just keep on saying that :laughing:

Four: two standalones and one double :p

**Comment by Deevad** [comment]
Hey @M1dgard and @Willem3141 is it ready to merge ?
I think the only remaining thing to do is to adjust the 'HIPPIAH' label on the box to 80.0 opacity ; and position it for the final artwork. Let me know. I'll release very soon now :)

**Comment by ghost** [comment]
I think it is.

**Comment by Deevad** [comment]
Thanks!

**Pull request merged**
