### PR TITLE
typos, minor text tweaks

### PR DESCRIPTION
**Pull request by colognella**

### CODE REVIEW

**Comment by Deevad** [comment]
Thank you! 
I sent invitation to be collaborator on all episode repo ; so you can directly push to master on each of them ( sometime it's a bit easier ).

**Comment by colognella** [comment]
Thanks for your trust! Is there a place to discuss consistency (across episodes) of a single translation with the other translators of a language? E.g. naming conventions, translation of specific words like "godmothers" in the context of Hereva etc.

**Comment by Deevad** [comment]
@colognella : Sure! 

First the Chat:
- IRC #pepper&carrot on Freenode
- Bridge of this IRC channel on Telegram: https://telegram.me/joinchat/BLVsYz_DIz-S-TJZB9XW7A
- Bridge of this IRC channel on Mattermost/Framateam: https://framateam.org/signup_user_complete/?id=gcaq67sntfgr5jbmoaogsgdfqc

Second, the shared Google doc for consistency of names , etc :
https://docs.google.com/spreadsheets/d/1zRqVAj8q1iHwOXQBplXp_DaoZyDgJ3uA0_st_iZEDGg/edit#gid=0

Third , the translation status table:
http://www.peppercarrot.com/en/static6/sources&page=translation

And last , the mailing list for translator:
https://groups.google.com/forum/#!forum/peppercarrot-translation-team

**Comment by Deevad** [comment]
All of this information probably needs work to be centralized into a single place ; sorry about this patchwork of link/data :)

**Comment by colognella** [comment]
looks familiar ;-)

**Pull request merged**
